### PR TITLE
fix error formatting in fmt.Errorf calls

### PR DESCRIPTION
**Pull request by hrtsegv**
Hello **Link-**

This pull request resolves error formatting issues by removing punctuation at the end of error strings and ensuring they are not capitalized. Improves code readability and adheres to **_best practices_**.

Thank you

### CODE REVIEW

**Review by Link- — CHANGES_REQUESTED** [review]
Thank you for contributing! I agree with this change. However, could you please remove the screenshot image?

I'll wait for the CI to pass before merging.

**Comment by hrtsegv** [comment]
Thank you for your feedback and considering the change! 
I have removed the screenshot as per your request. Let me know if there are any additional changes or considerations needed. 

Thanks again!

**Review by Link- — CHANGES_REQUESTED** [review]
:) it's still in the PR, delete it, stage it, commit and push from your fork

**Comment by hrtsegv** [comment]
Apologies for the confusion earlier. 😅 
I have rectified the mistake and successfully removed the screenshot from the pull request.

**Review by Link- — APPROVED** [review]

**Pull request merged**
